[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "pixel-font-builder"
version = "0.0.36"
description = "A library that helps create pixel style fonts"
readme = "README.md"
license = { text = "MIT License" }
requires-python = ">=3.12"
authors = [
    { name = "TakWolf" },
]
maintainers = [
    { name = "TakWolf" },
]
keywords = ["font", "pixel"]
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

dependencies = [
    "fonttools[woff]>=4.58.2",
    "bdffont>=0.0.32",
    "pcffont>=0.0.21",
]

[project.urls]
homepage = "https://github.com/TakWolf/pixel-font-builder"
source = "https://github.com/TakWolf/pixel-font-builder"
issues = "https://github.com/TakWolf/pixel-font-builder/issues"

[tool.pytest.ini_options]
pythonpath = "src"
addopts = [
    "--import-mode=importlib",
]
